### ISSUE TITLE
Feature: to-dos with text, link, co-doer, due

### ISSUE THREAD

**Issue by hongsw** [xide-projext/shell-we-study#1]

**Comment by Ziihong** [comment]
@hongsw 제가 생각해본 화면 구성입니다. 피드백 부탁드립니다!
그리고 due가 지난 목표들은 어떻게 관리하면 좋을지 고민됩니다.

![Image](https://user-images.githubusercontent.com/54922803/212672059-1859733f-94f5-46cb-bd6a-3bf1130ce61f.png)

![Image](https://user-images.githubusercontent.com/54922803/212672083-bc163e5a-c2c2-48fc-8651-0892592bb29c.png)

**Comment by hongsw** [comment]
구글 task를 봐도 특히 다른건없는데 필요하다면 나중에 보기 필터에 지난것만 보는 버튼을 만들어줄까요?

**Comment by hongsw** [comment]
> @hongsw 제가 생각해본 화면 구성입니다. 피드백 부탁드립니다!
> 그리고 due가 지난 목표들은 어떻게 관리하면 좋을지 고민됩니다.
> 
> ![Image](https://user-images.githubusercontent.com/54922803/212672059-1859733f-94f5-46cb-bd6a-3bf1130ce61f.png)
> 
> ![Image](https://user-images.githubusercontent.com/54922803/212672083-bc163e5a-c2c2-48fc-8651-0892592bb29c.png)
> 
> 

할거당 링크를 여러개 보다 1개가 좋지 않을까요 그 기능이 필요한 상황이 있겠지만 복잡성이 올라갈까봐서요

**Comment by Ziihong** [comment]
@hongsw 넵! 좋습니다. 의견 주셔서 감사합니다.
